"""update name length

Revision ID: 63389f1fbb36
Revises: 748dbc146350
Create Date: 2024-08-24 12:50:21.708538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63389f1fbb36'
down_revision = '748dbc146350'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)

    # ### end Alembic commands ###
