"""update user model again

Revision ID: 748dbc146350
Revises: 5ed11afc6d48
Create Date: 2024-07-13 22:36:06.007502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '748dbc146350'
down_revision = '5ed11afc6d48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.String(length=30), nullable=True))
    op.drop_column('user', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.VARCHAR(length=30), nullable=True))
    op.drop_column('user', 'username')
    # ### end Alembic commands ###
